name: Mobile frontend build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: mobile-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Use NodeJS 24.x
      uses: actions/setup-node@v5
      with:
        node-version: 24.x
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Export mobile frontend (build validation)
      run: npx nx export mobile-frontend
